model_params:  
  descrip: "First Test"
  model_name: "DeepDive"
  mode: "Train"
  log_dir: /media/mnt/dehaze/logs/

training_params:
  learning_rate: 1e-05
  epochs: 100
  batch_size: 16
  data_path: /media/mnt/dehaze/npy_files/
