model_params:  
  descrip: "Trying the learn the identity function."
  model_name: "DeepDive"
  mode: "Train"
  log_dir: /media/mnt/dehaze/logs/

training_params:
  learning_rate: 1e-04
  epochs: 5000
  batch_size: 16
  data_path: /media/mnt/dehaze/npy_files/
